name: Test Dotfiles Installation

on:
  push:
    branches:
      - '*'  # Trigger on pushes to any branch
  pull_request:
    branches:
      - '*'  # Trigger on pull requests to any branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up test environment
      run: |
        sudo apt-get update
        sudo apt-get install -y git curl wget python3 python3-pip

    - name: Create .gitconfig.secret
      run: |
        echo "[user]" > ~/.gitconfig.secret
        echo "name = ${{ secrets.GIT_USER_NAME }}" >> ~/.gitconfig.secret
        echo "email = ${{ secrets.GIT_USER_EMAIL }}" >> ~/.gitconfig.secret

    - name: Configure Git to include .gitconfig.secret
      run: |
        echo "[include]" > ~/.gitconfig
        echo "path = ~/.gitconfig.secret" >> ~/.gitconfig

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zsh

    - name: Install dotfiles
      run: |
        curl -fsSL https://oddish3.github.io/dotfiles/etc/install | bash

    - name: Change default shell to zsh
      run: |
        sudo chsh -s $(which zsh) $USER

    - name: Verify installation
      run: |
        set -e
        [ -d "$HOME/.dotfiles" ] || (echo ".dotfiles directory not found" && exit 1)
        for dir in bin config etc git nvim python tmux vim zsh; do
          [ -d "$HOME/.dotfiles/$dir" ] || (echo "$dir directory not found" && exit 1)
        done
        [ -f "$HOME/.dotfiles/install.py" ] || (echo "install.py not found" && exit 1)
        for file in .bashrc .gitconfig .vimrc .zshrc; do
          [ -L "$HOME/$file" ] || (echo "$file is not symlinked" && exit 1)
        done
        echo "Current shell: $SHELL"
        echo "All checks passed successfully!"

    - name: Verify zsh is default shell
      run: |
        if [ "$SHELL" != "$(which zsh)" ]; then
          echo "ZSH is not the default shell"
          exit 1
        fi