name: Test Dotfiles Installation

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v3

    - name: Cache packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/Library/Caches/pip
          /var/cache/apt/archives
        key: ${{ runner.os }}-packages-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-packages-

    - name: Set up test environment (Ubuntu)
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y git curl wget python3 python3-pip zsh

    - name: Create .gitconfig.secret
      run: |
        echo "[user]" > ~/.gitconfig.secret
        echo "name = ${{ secrets.GIT_USER_NAME }}" >> ~/.gitconfig.secret
        echo "email = ${{ secrets.GIT_USER_EMAIL }}" >> ~/.gitconfig.secret

    - name: Configure Git to include .gitconfig.secret
      run: |
        echo "[include]" > ~/.gitconfig
        echo "path = ~/.gitconfig.secret" >> ~/.gitconfig

    - name: Install dotfiles
      run: |
        set -x  # Enable verbose output
        curl -fsSL https://oddish3.github.io/dotfiles/etc/install | bash
        echo "Exit status: $?"

    - name: Verify installation
      run: |
        set -ex
        [ -d "$HOME/.dotfiles" ]
        for dir in bin config etc git nvim python tmux vim zsh; do
          [ -d "$HOME/.dotfiles/$dir" ]
        done
        [ -f "$HOME/.dotfiles/install.py" ]
        for file in .bashrc .gitconfig .vimrc .zshrc; do
          [ -L "$HOME/$file" ]
        done
        echo "Current shell: $SHELL"
        echo "All checks passed successfully!"